version: "2"

services:
  # REST API project needs a MYSQL server with host 'mysql'
  rest-api:
    build: .
    expose:
      - "8080"
    links:
     - mysql:mysql
    networks:
      - bridge-network
  # MYSQL server needs an initialise script and
  # environment variables to define the default user
  mysql:
    image: mysql
    env_file:
      - ./database/database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - bridge-network
networks:
  # Network between the API and the MYSQL server
  bridge-network:
    driver: bridge
