version: "2"

services:
  domain:
    build: .
    links:
     - mysql:mysql
    networks:
     - bridge-network
  mysql:
    build: db/acceptance/Dockerfile
    expose:
      - "3306"
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge
