version: "2"

services:
  domain:
    build: .
    links:
     - mysql:mysql
    networks:
     - bridge-network
  mysql:
    image: mysql
    expose:
      - "3306"
    env_file:
      - ./database/database.env
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - bridge-network
networks:
  bridge-network:
    driver: bridge
